In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [4]:
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369


In [5]:
len(df)

9704

In [6]:
df['fuel_type'].nunique()

2

In [7]:
df['fuel_type'].value_counts()

fuel_type
Gasoline    4898
Diesel      4806
Name: count, dtype: int64

In [8]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [9]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

In [10]:
df['horsepower'].describe()

count    8996.000000
mean      149.657292
std        29.879555
min        37.000000
25%       130.000000
50%       149.000000
75%       170.000000
max       271.000000
Name: horsepower, dtype: float64

In [11]:
df['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [13]:
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mode())

In [14]:
df['horsepower'].median()

np.float64(149.0)

In [22]:
x = np.array(df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']].head(7))

In [23]:
x

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [24]:
xtx = x.dot(x.T)

In [25]:
xtx

array([[11431242.46085133, 11608190.92541486, 13770311.23387465,
        10111792.75336224, 11282536.19632532, 11780081.29349753,
        14281180.86123177],
       [11608190.92541486, 11790026.46575708, 14007802.20739725,
        10255171.44187306, 11455668.70489329, 11966096.78727446,
        14531088.48421337],
       [13770311.23387465, 14007802.20739725, 16863697.77478558,
        12031947.83608462, 13574023.463935  , 14232076.05656009,
        17530181.51805091],
       [10111792.75336224, 10255171.44187306, 12031947.83608462,
         9025088.58092514,  9989516.7638366 , 10397924.16669749,
        12456257.9230991 ],
       [11282536.19632532, 11455668.70489329, 13574023.463935  ,
         9989516.7638366 , 11136831.64128077, 11624252.15672766,
        14075069.26273247],
       [11780081.29349753, 11966096.78727446, 14232076.05656009,
        10397924.16669749, 11624252.15672766, 12145826.2645139 ,
        14766233.02574041],
       [14281180.86123177, 14531088.48421337, 175301

In [26]:
xtx_inv = np.linalg.inv(xtx)

In [30]:
xtx_inv

array([[ 5.14065606e+08,  5.48536130e+07, -3.76831385e+08,
        -5.99044087e+08,  4.10105044e+08, -7.87026143e+07,
         7.23633092e+07],
       [ 3.29129898e+08,  8.26109025e+08, -3.72548813e+08,
        -7.01583859e+08,  3.27222378e+07, -5.67206124e+07,
        -5.80223502e+07],
       [-6.16516597e+08, -2.64221399e+08,  2.93298395e+08,
         7.94190283e+08, -1.94689452e+08, -1.53391689e+08,
         1.43457519e+08],
       [-4.98522990e+08, -2.71174593e+08,  5.34131775e+08,
         7.89486336e+08, -2.49261495e+08, -2.49261495e+08,
        -5.20318918e+07],
       [-0.00000000e+00, -2.68435456e+08,  2.23517418e-07,
         2.03703699e+08, -2.68435456e+08,  2.68435456e+08,
         6.46082210e+07],
       [ 0.00000000e+00, -1.15043767e+08, -1.15043767e+08,
        -2.70361224e+08,  2.68435456e+08,  2.68435456e+08,
        -3.76263766e+07],
       [ 2.68435456e+08,  3.83479223e+07,  3.83479223e+07,
        -2.12927011e+08,  0.00000000e+00,  0.00000000e+00,
        -1.3225025

In [31]:
xtx_inv.shape

(7, 7)

In [27]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [28]:
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [32]:
w = xtx_inv * x.T 

ValueError: operands could not be broadcast together with shapes (7,7) (2,7) 